# puts 'Deleting existing ingredients'
# Ingredient.destroy_all
# puts 'Creating new ingredients'
# Ingredient.create(name: "Angostura")
# Ingredient.create(name: "Aperol")
# Ingredient.create(name: "Apple brandy")
# Ingredient.create(name: "Berries")
# Ingredient.create(name: "Bitters")
# Ingredient.create(name: "Black pepper")
# Ingredient.create(name: "Blended whiskey")
# Ingredient.create(name: "Bourbon")
# Ingredient.create(name: "Cachaça")
# Ingredient.create(name: "Campari")
# Ingredient.create(name: "Carbonated water")
# Ingredient.create(name: "Celery")
# Ingredient.create(name: "Club soda")
# Ingredient.create(name: "Cocoa powder")
# Ingredient.create(name: "Coconut milk")
# Ingredient.create(name: "Coffee liqueur")
# Ingredient.create(name: "Cramberry juice")
# Ingredient.create(name: "Gin")
# Ingredient.create(name: "Gin")
# Ingredient.create(name: "Ginger")
# Ingredient.create(name: "Gomme syrup")
# Ingredient.create(name: "Ice")
# Ingredient.create(name: "Lager")
# Ingredient.create(name: "Lemon")
# Ingredient.create(name: "Light rum")
# Ingredient.create(name: "Liquor")
# Ingredient.create(name: "Mint leaves")
# Ingredient.create(name: "Orange")
# Ingredient.create(name: "Peach schnapps")
# Ingredient.create(name: "Peppermint schnapps")
# Ingredient.create(name: "Pineapple juice")
# Ingredient.create(name: "Pisco")
# Ingredient.create(name: "Prosecco")
# Ingredient.create(name: "Rum")
# Ingredient.create(name: "Salt")
# Ingredient.create(name: "Scotch")
# Ingredient.create(name: "Sparkling wine")
# Ingredient.create(name: "Sugar syrup")
# Ingredient.create(name: "Sugar")
# Ingredient.create(name: "Sweet Vermouth")
# Ingredient.create(name: "Tabasco")
# Ingredient.create(name: "Tomato juice")
# Ingredient.create(name: "Vermute")
# Ingredient.create(name: "Vodka")
# Ingredient.create(name: "Other")
# puts 'Ingredients created!'



Cocktail.destroy_all
puts 'Ingredients creating!'
Ingredient.create(name: "Morango")
Ingredient.create(name: "Banana")
Ingredient.create(name: "Maça")
puts 'Ingredients created!'